spring.application.name=galeri_project
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=gallerist
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION} 

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

tcmb.api.key=${TCMB_KEY}
tcmb.api.base-url=https://evds2.tcmb.gov.tr/service/evds
tcmb.api.series=TP.DK.USD.A

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

app.oauth2.redirect-uri=http://localhost:8080/Oauth
